import React, { useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';

function ProjectDetail(props) {
    console.log(props.id);
    const mainRef = useRef(null);

    useEffect(() => {
        mainRef.current.focus();
    }, [])

    return (
        <section className="s2">
            <div className="postdetail-wrapper">
                <div ref={mainRef} tabIndex="0" className="nav-wrapper">
                    <Link to='/'>
                        <div className="dots-wrapper">
                            <div id="dot-1" className="browser-dot"></div>
                            <div id="dot-2" className="browser-dot"></div>
                            <div id="dot-3" className="browser-dot"></div>
                        </div>
                    </Link>

                    <ul id="navigation">
                        <li><a style={{marginRight: 20}} href={"#about"}>About</a></li>
                        <li><a style={{marginRight: 20}} href={"#contact"}>Contact</a></li>
                        <li><a href={"#portfolio"}>Projects</a></li>
                    </ul>
                </div>

                <div className="main-container">
                    <br/>

                    <div className="img-container">
                        <img src="images/dash.jpg"/>
                    </div>

                    <h3>{props.data.projecttitle}</h3>

                    <p>This was a project I started back in november 2017 when I first learned python. I was the sole creator/developer for the first year of the project before I was able to hire help.
                    <br/>
                    <br/>
                    The system stored fuel sample data for the entire lab and provided an interface for lab chemists and admins to view, add and send data to clients.
                    <br/>
                    <br/>
                    Lab results would be generated by the system in PDF form and automatically sent to the client along with an interface for customers to be able to login and view.
                    <br/>
                    <br/>
                    Customers had the ability to view all their data with a dynamic search form, trend data, add notes to reports and even map their samples' physical location.
                    <br/>
                    <br/>
                    I worked on this system for 2 years before selling this to FOI Laboratories.</p>

                    <h5>Technologies:</h5>
                    <ul>
                        <li>- Python</li>
                        <li>- Django + Django REST Framework</li>
                        <li>- React JS</li>
                        <li>- Postgres</li>
                        <li>- AWS (S3 &span; RDS)</li>
                        <li>- Zingcharts - Trending &span; graphing test results</li>
                        <li>- Google Maps API</li>
                        <li>- XML2PDF - PDF generator</li>
                    </ul>


                    <h5>Laboratory Admin Dashboard</h5>
                    <div className="img-container">
                        <img src="images/lab-dash.jpg"/>
                    </div>

                    <h5>Sample ID Form</h5>
                    <div className="img-container">
                        <img src="images/sample-form.jpg"/>
                    </div>

                    <h5>Results Input Fields</h5>
                    <div className="img-container">
                        <img src="images/results.jpg"/>
                    </div>

                    <h5>PDF Report (Automaticly Generated)</h5>
                    <div className="img-container">
                        <img src="images/pdf-report.jpg"/>
                    </div>

                    <h5>Customer Dashboard</h5>
                    <div className="img-container">
                        <img src="images/customer-dash.jpg"/>
                    </div>

                </div>
            </div>
        </section>
    );
}

export default ProjectDetail;